### PR TITLE
Updates for the navbar, footer and welcome page

### PR DESCRIPTION
**Pull request by dariusdv**
Implementation for the navbar, footer and "welcome" component updates from issue https://github.com/spring-petclinic/spring-petclinic-angular/issues/121.

### CODE REVIEW

**Comment by arey** [comment]
@dariusdv did you have any screenshot?
By the way, I dont know why the 16.x build has failed. I have to investigate

**Comment by dariusdv** [comment]
Hi @arey, 
Yes, the Home page will be like in this screenshot after the updates

image

**Comment by arey** [comment]
Could you try to upgrade the `@angular/cdk` in your PR please?
Once merged, you could work on the Angular 16 upgrade. It would be much appreciated 👍

**Comment by arey** [comment]
It's working. Great!

**Pull request merged**
