### PR TITLE
Form validation for pets, pettype, visits, specialities

### PR DESCRIPTION
**Pull request by simrin051**

### CODE REVIEW

**Comment by simrin051** [comment]
Hi @arey 

Can you please review and merge if seems to be good.

**Comment by simrin051** [comment]
@arey 

Can you please review the code

**Comment by simrin051** [comment]
Hi @arey 
Can you please review the code

**Comment by arey** [comment]
It looks like your PR is mixing `search` and `validation` features. Could you remove the `search` part merged in another PR?

**Comment by simrin051** [comment]
@Arey can you please check now.

I have used below commands
git add .
git reset --  src/app/owners/owner-edit/owner-list.component.html [ To avoid this file ]
git push origin form-validation

**Comment by arey** [comment]
It souds like of me. Thanks a lot.
Are you interested in continuing the Angular 11 upgrade work started in PR #53?

**Comment by simrin051** [comment]
Thanks @arey . I can continue with Angular 11 upgrade work.

I have a request @arey 
I am participating in Hacktober fest. It is a fest that promotes open source contribution. Can you please label my contribution as hacktoberfest-accepted  for those pull requests created and merged in the month of October with the label hacktoberfest-accepted.

**Comment by arey** [comment]
Hi @simrin051, sure, i've added the `hacktoberfest-accepted` label

**Comment by simrin051** [comment]
Thanks @arey

**Pull request merged**
