### PR TITLE
tests for owner component and specialty-add component

### PR DESCRIPTION
**Pull request by simrin051**

### CODE REVIEW

**Comment by simrin051** [comment]
@arey 

When running ng test i get the below error when jasmine karma clicks on Update Owner . It is working fine when i run ng serve. I tried many times to rectify but it is the same error.  Can you please advice.

**Comment by simrin051** [comment]
@arey

When running ng test i get the below error when jasmine karma clicks on Update Owner . It is working fine when i run ng serve. I tried many times to rectify but it is the same error. Can you please advice.

ERROR: 'ERROR', TypeError: this.ownerService.updateOwner is not a function
TypeError: this.ownerService.updateOwner is not a function
    at OwnerEditComponent.PR5q.OwnerEditComponent.onSubmit (http://localhost:9876/_karma_webpack_/webpack:/src/app/owners/owner-edit/owner-edit.component.ts:56:23)
    at listenerFn (ng:///OwnerEditComponent.js:113:22)
    at executeListenerWithErrorHandling (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15265:16)

**Comment by alexandre-touret** [comment]
Hi @simrin051 
We pushed a new feature on this project promoting a contract first approach.
Unfortunately, there are some breaking changes.

You can refer to this [open api yaml description](https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/resources/api-docs.yml).

Concerning your maven error, normally it should work. Perhaps, it's due to your maven configuration.
Regards

**Comment by simrin051** [comment]
> Hi @simrin051 We pushed a new feature on this project promoting a contract first approach. Unfortunately, there are some breaking changes.
> 
> You can refer to this [open api yaml description](https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/resources/api-docs.yml).
> 
> Concerning your maven error, normally it should work. Perhaps, it's due to your maven configuration. Regards

Thanks @alexandre-touret 
Yeah i resolved the maven error, but are you saying that the error i am facing in test cases is because of the new changes. I do not think so because it is working fine with ng serve, but throwing the error with ng test.

**Comment by simrin051** [comment]
@arey 

Can you please check.

**Comment by simrin051** [comment]
@arey 
Can you please check.

**Comment by arey** [comment]
Thank you @simrin051

**Pull request merged**
