### PR TITLE
tslint to eslint migration

### PR DESCRIPTION
**Pull request by simrin051**

### CODE REVIEW

**Comment by simrin051** [comment]
@arey 
i have completed migration. Kindly requesting you to please merge if there are no issues.

**Comment by arey** [comment]
Good job, thanks. I still see the `tslint.json` file. Could you be sure please to remove all tslint reference?

**Comment by simrin051** [comment]
@arey 

Can you please check now

**Comment by simrin051** [comment]
@arey  May i know whether  i should use git add . so that it shows tslint.json is deleted.

**Comment by simrin051** [comment]
@arey 
Can you please check now.

**Comment by arey** [comment]
Thanks a lot simrin051

**Pull request merged**
