### PR TITLE
Added test cases for owner component

### PR DESCRIPTION
**Pull request by simrin051**

### CODE REVIEW

**Comment by simrin051** [comment]
Hi @arey 

Can you please review. I will write test cases for remaining components as well.

**Comment by simrin051** [comment]
Hi @arey / @vfedoriv 

I have written test cases for owner component for those were test cases were missing. Can you please review. Please.

**Comment by simrin051** [comment]
Hi @arey / @vfedoriv

I have written test cases for owner component for those were test cases were missing. Can you please review. Please.

**Comment by arey** [comment]
Thanks @simrin051 for the missing unit tests.
In your PR, could you remove reformat commit pleate to focus on the tests?

**Comment by simrin051** [comment]
@arey 
May i know whether you want me to remove 
'cleanup of owner add and owner detail this commit'. I have removed it , can you please check now.

**Comment by simrin051** [comment]
@arey  Can you please check now.

I have made changes to owner add, owner detail ,owner list, owner service, and bug fix of speciality add component

**Comment by simrin051** [comment]
@arey Can you please check now

**Comment by arey** [comment]
Is it possible please to not reformat html pages like `owner-add.component.html`?

**Comment by simrin051** [comment]
yes sure, I fixed a bug in speciality add component html.  It was making a test case fail.

**Comment by simrin051** [comment]
@arey  will it work if i commit again without committing html files for owner. For speciality add component html change is needed to pass a test case. Can you please advice.

**Comment by arey** [comment]
If you check global files changed https://github.com/spring-petclinic/spring-petclinic-angular/pull/67/files you will see a lot of files that are not tests. You may revert all of those files or choose to create another branch from `master` and cherry pick the test files.

**Comment by arey** [comment]
Please reopen if needed

**Pull request closed without merging**
